### ISSUE TITLE
Guests are missing on viewonline.php for non-admins

### ISSUE THREAD

**Issue by Nekstati** [rmcgirr83/hidebots#1]
- Login as a regular user
- Go to viewonline.php
- Click "Display guests"
- No effect

The cause is here:
https://github.com/rmcgirr83/hidebots/blob/a7b7019a1dbbbaf532227de9a5e792394b01cb29/event/listener.php#L139
USER_IGNORE means both "guest" and "bot".

**Comment by rmcgirr83** [comment]
Why does this matter for non-admins?

**Comment by rmcgirr83** [comment]
Closing due to no comment. Assuming it's not an issue.

**Comment by Nekstati** [comment]
> Why does this matter for non-admins?

phpBB by default shows guests to non-admins, whether it matters or not. When this extension is enabled, the function is broken: someone sees "100 guests online", clicks "Display guests", and sees no guests. The label changes to "0 guests online". Then he/she clicks "Hide guests" and sees "100 guests online" again. It's definitely not a big issue, but it's a bug.
